version: '3.8'

services:
  l0wb:
    build: ./
    container_name: l0wb_container
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - nats
      - migrate
    networks:
      - mynetwork
  db:
    image: postgres
    container_name: db_container
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_TABLE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  nats:
    image: 'synadia/nats-server:nightly'
    ports:
      - 4222:4222
    volumes:
      - ./.jetstream:/tmp/nats
    entrypoint: ["nats-server", "-js"]
    networks:
      - mynetwork
    restart: always
  migrate:
    image: migrate/migrate
    container_name: migrate_container
    volumes:
      - ./schema:/migration
    networks:
      - mynetwork
    entrypoint:
      [
        "migrate",
        "-path",
        "/migration",
        "-database",
        "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_TABLE}?sslmode=${DB_SSLMODE}",
      ]
    command: ["up"]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

networks:
  mynetwork:
    driver: bridge